[project]
name = "av-fleet-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bronson Hill", email = "bronson.hill@yahoo.com.au" }
]
requires-python = ">=3.13"
dependencies = [
    "altair>=6.3.0",
    "ipyvue<2",
    "ipyvuetify<2",
    "mesa>=3.5.1",
    "networkx>=3.7",
    "seaborn>=0.13.2",
    "solara>=1.62.0",
]

[project.scripts]
av-fleet-simulation = "av_fleet_simulation:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
